stages:
  - lint
  - test


lint-frontend:
  stage: lint
  image: node:18-alpine
  before_script:
    - cd frontend  
  script:
    - echo "Starting Frontend linting..."
    - npm ci --legacy-peer-deps
    - npm run lint
    - npm run lint:fix
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

  allow_failure: false  


test-frontend:
  stage: test
  image: node:18-alpine
  needs: ["lint-frontend"]
  before_script:
    - cd frontend
  script:
    - echo "Running Frontend Tests"
    - npm ci --legacy-peer-deps
    - npm test -- --coverage --watchAll=false --coverageReporters=text-summary
  coverage: '/Lines\s*:\s*(\d+(?:\.\d+)?%)/'
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

  allow_failure: false  


lint-backend:
  stage: lint
  image: gradle:8.5-jdk17
  cache:
    key: backend-gradle-cache
    paths:
      - /home/gradle/.gradle/
      - .gradle/
  before_script:
    - cd backend
  script:
    - echo "Starting Backend linting"
    -  ./gradlew checkstyleMain spotbugsMain
  rules: 
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

  allow_failure: false 


test-backend:
  stage: test
  image: gradle:8.5-jdk17
  needs: ["lint-backend"]
  cache:
    key: backend-gradle-cache
    paths:
      - /home/gradle/.gradle/
      - .gradle/
  before_script:
    - cd backend
  script:
    - echo "Starting Backend Testing"
    - ./gradlew --no-daemon clean test jacocoTestReport printJacocoSummary
  coverage: '/Lines:\s+\d+\/\d+\s+\((\d+%)/'
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

  allow_failure: false

  artifacts:
    reports:
      junit: backend/build/test-results/**/*.xml
    paths:
      - backend/build/reports/jacoco/
      - backend/build/test-results/
    when: always
    expire_in: 30 days
    